#
# destroys:
#   - any external mounts of the cidata or vm fs (halts if in use)
#   - previously created virtual machine, if it exists
#   - vm filesystem and volume
#   - cidata filesystem and volume
---

- include: destroy-vm.yml
- include: unmount-cidata.yml
- include: unmount-vmroot.yml
- include: remove-lvols.yml
